/**
 * ipfs-archive
 * The web api for ipfs-archive
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ArchiveRequest', 'model/ArchiveResponse', 'model/Error'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ArchiveRequest'), require('../model/ArchiveResponse'), require('../model/Error'));
  } else {
    // Browser globals (root is window)
    if (!root.IpfsArchive) {
      root.IpfsArchive = {};
    }
    root.IpfsArchive.IpfsApi = factory(root.IpfsArchive.ApiClient, root.IpfsArchive.ArchiveRequest, root.IpfsArchive.ArchiveResponse, root.IpfsArchive.Error);
  }
}(this, function(ApiClient, ArchiveRequest, ArchiveResponse, Error) {
  'use strict';

  /**
   * Ipfs service.
   * @module api/IpfsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new IpfsApi. 
   * @alias module:api/IpfsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the archiveUrl operation.
     * @callback module:api/IpfsApi~archiveUrlCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArchiveResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Archive a URL
     * @param {module:model/ArchiveRequest} body The URL to archive
     * @param {module:api/IpfsApi~archiveUrlCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ArchiveResponse}
     */
    this.archiveUrl = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling archiveUrl");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ArchiveResponse;

      return this.apiClient.callApi(
        '/archive', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
