// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi ipfs-archive
The web api for ipfs-archive


    Schemes:
      http
    Host: localhost:7002
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
