// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The web api for ipfs-archive",
    "title": "ipfs-archive",
    "version": "1.0.0"
  },
  "host": "ipfs.archive.network",
  "basePath": "/api",
  "paths": {
    "/archive": {
      "post": {
        "tags": [
          "ipfs"
        ],
        "summary": "Archive a URL",
        "operationId": "archiveUrl",
        "parameters": [
          {
            "description": "The URL to archive",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ArchiveRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Archive Response",
            "schema": {
              "$ref": "#/definitions/ArchiveResponse"
            }
          },
          "500": {
            "description": "Archive Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ArchiveRequest": {
      "type": "object",
      "required": [
        "url"
      ],
      "properties": {
        "url": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "ArchiveResponse": {
      "type": "object",
      "properties": {
        "archived_url": {
          "type": "string",
          "readOnly": true
        },
        "id": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "readOnly": true
        }
      }
    }
  }
}`))
}
