/**
 * ipfs-archive
 * The web api for ipfs-archive
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IpfsArchive) {
      root.IpfsArchive = {};
    }
    root.IpfsArchive.ArchiveResponse = factory(root.IpfsArchive.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ArchiveResponse model module.
   * @module model/ArchiveResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ArchiveResponse</code>.
   * @alias module:model/ArchiveResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ArchiveResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArchiveResponse} obj Optional instance to populate.
   * @return {module:model/ArchiveResponse} The populated <code>ArchiveResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('archived_url')) {
        obj['archived_url'] = ApiClient.convertToType(data['archived_url'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} archived_url
   */
  exports.prototype['archived_url'] = undefined;



  return exports;
}));


