/**
 * ipfs-archive
 * The web api for ipfs-archive
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.IpfsArchive) {
      root.IpfsArchive = {};
    }
    root.IpfsArchive.ArchiveRequest = factory(root.IpfsArchive.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ArchiveRequest model module.
   * @module model/ArchiveRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ArchiveRequest</code>.
   * @alias module:model/ArchiveRequest
   * @class
   * @param url {String} 
   */
  var exports = function(url) {
    var _this = this;

    _this['url'] = url;
  };

  /**
   * Constructs a <code>ArchiveRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ArchiveRequest} obj Optional instance to populate.
   * @return {module:model/ArchiveRequest} The populated <code>ArchiveRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;



  return exports;
}));


