// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ArchiveResponse archive response
// swagger:model ArchiveResponse

type ArchiveResponse struct {

	// archived url
	// Read Only: true
	ArchivedURL string `json:"archived_url,omitempty"`

	// id
	// Read Only: true
	ID string `json:"id,omitempty"`
}

/* polymorph ArchiveResponse archived_url false */

/* polymorph ArchiveResponse id false */

// Validate validates this archive response
func (m *ArchiveResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ArchiveResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArchiveResponse) UnmarshalBinary(b []byte) error {
	var res ArchiveResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
